azure_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}
  keyvault_name: ${KEYVAULT_NAME}
  compute_target: ${COMPUTE_TARGET}
  
connections:
- connection: aoai
  api_type: azure
  api_key: ${AZURE_OPENAI_KEY}
  api_base: ${AZURE_OPENAI_ENDPOINT}
  api_version: ${AZURE_OPENAI_API_VERSION}

experiment:
  name: named_entity_recognition
  flow: flows/standard

  datasets:
  - name: named_entity_recognition_train
    source: data/data.jsonl
    description: "This dataset is for prompt experiments."
    mappings:
      text: "${data.text}"
      entity_type: "${data.entity_type}"

  evaluators:
  - name: matcher
    flow: flows/evaluation
    datasets:
    - name: named_entity_recognition_test
      reference: named_entity_recognition_train
      source: data/eval_data.jsonl
      description: "This dataset is for evaluating flows."
      mappings:
        ground_truth: "${data.results}"
        entities: "${run.outputs.entities}"

environments:
  pr:
    env_name: pr

    experiment:
      name: named_entity_recognition

      datasets:
      - name: named_entity_recognition_pr
        source: data/data.jsonl
        description: "This dataset is for pr validation only."
        
        mappings:
          text: "${data.text}"
          entity_type: "${data.entity_type}"

      evaluators:

  dev:
    env_name: dev
    
    experiment:

    deployment_configs:
      azure_managed_endpoint:
      - name: azure_managed_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME: 
        ENDPOINT_DESC: An online endpoint serving a flow for named entity flow
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME: 
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
        CURRENT_DEPLOYMENT_NAME:
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: "100"
        DEPLOYMENT_VM_SIZE: Standard_F4s_v2
        DEPLOYMENT_INSTANCE_COUNT: 1
        ENVIRONMENT_VARIABLES: 
          example-name: example-value
      
      kubernetes_endpoint:
      - name: kubernetes_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME:
        ENDPOINT_DESC: An kubernetes endpoint serving a flow for named entity
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME:
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
        CURRENT_DEPLOYMENT_NAME:
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: 100,
        COMPUTE_NAME:
        DEPLOYMENT_VM_SIZE:
        DEPLOYMENT_INSTANCE_COUNT: 1
        CPU_ALLOCATION: 
        MEMORY_ALLOCATION: 
        ENVIRONMENT_VARIABLES: 
          example-name: example-value
      
      webapp_endpoint:
      - name: webapp_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        CONNECTION_NAMES:
          - aoai
        REGISTRY_NAME:
        REGISTRY_RG_NAME:
        APP_PLAN_NAME:
        WEB_APP_NAME:
        WEB_APP_RG_NAME:
        WEB_APP_SKU: "B3"
        USER_MANAGED_ID:

  postprod:
    env_name: postprodeval
    
    experiment:
      name: named_entity_recognition
      flow: flows/post-production-evaluation

      datasets:
      - name: named_entity_recognition_pp_eval
        source: data/production_log.jsonl
        description: "This dataset is for post production evaluation."
        mappings:
          text: "${data.text}"
          entity_type: "${data.entity_type}"

      evaluators: 