azure_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}
  keyvault_name: ${KEYVAULT_NAME}
  compute_target: ${COMPUTE_TARGET}
  
connections:
- connection: aoai
  api_type: azure
  api_key: ${AZURE_OPENAI_KEY}
  api_base: ${AZURE_OPENAI_ENDPOINT}
  api_version: ${AZURE_OPENAI_API_VERSION}

experiment:
  name: chat_with_pdf
  flow: flows/standard

  datasets:
  - name: chat_with_pdf
    source: data/bert-paper-qna-3-line.jsonl
    description: "This dataset is for prompt experiments."
    mappings:
      math_question: "${data.question}"

  evaluators:
  - name: chat_with_pdf_evaluation_flow
    flow: flows/evaluation
  
    datasets:
    - name: chat_with_pdf_test
      reference: chat_with_pdf
      source: data/data.jsonl
      description: "This dataset is for evaluating flows."
      mappings:
        groundtruth: "${data.groundtruth}"
        prediction: "${run.outputs.answer}"

environments:
  pr:
    env_name: pr

    experiment:
      name: standard

      datasets:
      - name: chat_with_pdf_pr
        source: data/bert-paper-qna-1-line.jsonl
        description: "This dataset is for pr validation only."
        mappings:
          math_question: "${data.question}"

      evaluators:
  
  dev:
    env_name: dev

    experiment:

    deployment_configs:
      azure_managed_endpoint:
      - name: azure_managed_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME: 
        ENDPOINT_DESC: An online endpoint serving a flow for chat with pdf flow
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME: 
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
        CURRENT_DEPLOYMENT_NAME:
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: "100"
        DEPLOYMENT_VM_SIZE: Standard_F4s_v2
        DEPLOYMENT_INSTANCE_COUNT: 1
        ENVIRONMENT_VARIABLES: 
          example-name: example-value
            
      kubernetes_endpoint:
      - name: kubernetes_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME:
        ENDPOINT_DESC: An kubernetes endpoint serving a flow for chat with pdf
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME:
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
        CURRENT_DEPLOYMENT_NAME:
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: 100,
        COMPUTE_NAME:
        DEPLOYMENT_VM_SIZE:
        DEPLOYMENT_INSTANCE_COUNT: 1
        CPU_ALLOCATION: 
        MEMORY_ALLOCATION: 
        ENVIRONMENT_VARIABLES: 
          example-name: example-value
           
      webapp_endpoint:
      - name: webapp_endpoint_1
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        CONNECTION_NAMES:
          - aoai
        REGISTRY_NAME:
        REGISTRY_RG_NAME:
        APP_PLAN_NAME:
        WEB_APP_NAME:
        WEB_APP_RG_NAME:
        WEB_APP_SKU: "B3"
        USER_MANAGED_ID:   